apiVersion: v1
kind: Service
metadata:
  name: sample-application-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  selector:
    app: sample-application

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-application
  template:
    metadata:
      labels:
        app: sample-application
    spec:
      containers:
        - name: sample-application
          image: nevzatseferoglu/sample-application:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe: # prevents deadlock
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe: # prevents deadlock
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1

# Readiness probes indicate when an application is ready to serve traffic.
# If a readiness check fails then the container will be marked as not ready and will be removed from any load balancers.

# Liveness probes indicate a container is alive. If a liveness probe fails multiple times, then the container will be restarted.